/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9dfc052122fc89638a7e5bd348b8cd68)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		D1_NAME: string;
		R2: R2Bucket;
		chat_app_avatars: R2Bucket;
		chat_appd1: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "D1_NAME">> {}
}
