/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f6dce8482b1d06e60088342e154391f3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		R2: R2Bucket;
		chat_appd1: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
